#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zipline"
name = "Zipline"
description.en = "ShareX/file upload server"
description.fr = "Serveur de téléchargement ShareX/fichier"

version = "4.1.0~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://zipline.diced.sh/"
admindoc = "https://zipline.diced.sh/docs/get-started"
code = "https://github.com/diced/zipline"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "1500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/diced/zipline/archive/refs/tags/v4.1.0.tar.gz"
    sha256 = "7f98121ea51dacc0b4b5f9ce588c6e3fab934b456d66874f87571e0c021e4027"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["uploads"]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"
    api.auth_header = false

    [resources.ports]

    [resources.apt]
    packages = "postgresql, ffmpeg, tzdata"

    [resources.database]
    type = "postgresql"
