#!/bin/bash


source /usr/share/yunohost/helpers

secret=$(ynh_string_random --length=32)
ynh_app_setting_set --app="$app" --key=secret --value=$secret

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod 755 "$data_dir/uploads"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="ShareX/file upload server" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL ZIPLINE
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app COREPACK_ENABLE_DOWNLOAD_PROMPT=0 pnpm install
	ynh_hide_warnings ynh_exec_as_app ZIPLINE_BUILD=true pnpm build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
