#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep = ".env"

chmod 755 "$data_dir/uploads"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

ynh_nodejs_install

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating $app's configuration files..." --weight=1

ynh_add_config --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL ZIPLINE
#=================================================
ynh_script_progression --message="Building $app..." --weight=10

pushd $install_dir
 	ynh_use_nodejs
	ynh_exec_warn_less env $ynh_node_load_PATH corepack enable
	ynh_exec_warn_less env $ynh_node_load_PATH corepack prepare pnpm@latest --activate
	ynh_exec_warn_less ynh_exec_as "$app" env $ynh_node_load_PATH COREPACK_ENABLE_DOWNLOAD_PROMPT=0 pnpm install
	ynh_exec_warn_less ynh_exec_as "$app" env $ynh_node_load_PATH pnpm build
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="ShareX/file upload server" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL ZIPLINE
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app yarn install
	ynh_hide_warnings ynh_exec_as_app yarn build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
